name: Docker Image CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true

      - name: QEMU
        uses: docker/setup-qemu-action@v3

      - name: Logowanie Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Logowanie do GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set short SHA
        id: set_short_sha
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Build and push multi-platform image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            ghcr.io/gadziorwth/zadanie1:latest
            ghcr.io/gadziorwth/zadanie1:${{ steps.set_short_sha.outputs.SHORT_SHA }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/zad2-repo:builder
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/zad2-repo:builder,mode=max
          provenance: false

      - name: Trivy
        uses: aquasecurity/setup-trivy@ff1b8b060f23b650436d419b5e13f67f5d4c3087

      - name: Run Trivy
        run: |
          trivy image \
            --ignorefile .trivyignore \
            --exit-code 1 \
            --ignore-unfixed \
            --severity CRITICAL,HIGH \
            --vuln-type os,library \
            ghcr.io/gadziorwth/zadanie1:latest
